### ISSUE TITLE
time from click to animation start is long. how to shorten?

### ISSUE THREAD

**Issue by jabbermarky** [regexident/DLWidgetMenu#9]
when I click on the main menu item, the time for the animation to start (expand,contract) is too long for my tastes. how can I shorten that duration?

not a bug, just not obvious where to change.

**Comment by regexident** [comment]
The animation starts immediately. It just appears to be delayed.
That's due to the menu items moving underneath the main item.

If you want to take a look at the logic: 
`- (void)openAnimated:(BOOL)animated` and
`- (void)closeAnimated:(BOOL)animated` in `DLWMMenu`
are your friend. :smiley:
